### ISSUE TITLE
Projects page

### ISSUE THREAD

**Issue by domoritz** [uwdb/website#10]
Short description and papers for the projects. 
- current
- recently completed
- past

**Comment by domoritz** [comment]
How about a link to all the paper on dblp. Similar to http://db.cs.berkeley.edu/

**Comment by BrandonHaynes** [comment]
Logos added in 6f8bcd879bb1f43d438fbba8dfda21d44a27a32f.
Papers added in b7bb3b2b845a1f66fd5b62037652879ce441fadd.  Note that authors are drawn from a new dblp attribute on the people page.  Only the faculty are included at the moment.
