### ISSUE TITLE
Copy nwdb page

### ISSUE THREAD

**Issue by domoritz** [uwdb/website#11]

**Comment by domoritz** [comment]
@ljorr1 Is this finished? If yes, can you make sure that we add a redirect from the old page to the new page once it's online?

**Comment by stechu** [comment]
The links on this page are broken. FYI.

**Comment by ljorr1** [comment]
Hey, I realized I had my notification settings wrong and wasn't getting any emails about this. I am really sorry I didn't respond. The only problem is still that the links are broken. We need to add the past_talks.htm page somewhere or somehow put the data in the repo so Jeykll can format it. I have the past_talks.htm page ready.

**Comment by domoritz** [comment]
Can you just add a new page and convert the html to markdown? It's best to put that file in a nwdb subdirectory.

**Comment by ljorr1** [comment]
I made a branch with my changes. The only problem is that on /cse/www2/db/nwds (where old website was), there were a bunch of pdf and video files. I didn't want to push those to github but I don't know where to put them so that db.cs.washington.edu/nwds/pdf/ works.

**Comment by domoritz** [comment]
Can we put the videos on youtube and host the pdfs somewhere is CSE? You are right, we don't want large files on github as it makes git very slow.

**Comment by akcheung** [comment]
Isn't /cse/www2/db/nwds www-accessible?

**Comment by domoritz** [comment]
http://nwds.cs.washington.edu/

**Comment by ljorr1** [comment]
But we wanted to make nwds.cs.washington.edu redirect to the new page, correct? That's the old one. And this doesn't fix the problem of other pages that need to host pdfs/videos. I still vote for putting them in some CSE WWW directory that we can point to.

**Comment by akcheung** [comment]
/cse/www2/\* on the dept machines are www accessible. We could have used 
the db directory there but that won't work anymore due to the 
redirection. Should we ask support to create a nwds-repo directory under 
/cse/www2 and put everything there? And then we can ask them to redirect 
nwds.cs.washington.edu as well.

**Comment by mbalazin** [comment]
That sounds fine to me.

Magdalena Balazinska
Jean Loup Baer Professor of Computer Science and Engineering
Associate Professor, Dept. of Computer Science & Engineering
Director of the IGERT PhD Program in Big Data / Data Science
Senior Data Science Fellow of the eScience Institute
University of Washington

**Comment by BrandonHaynes** [comment]
S3 is another option here that would require a bit less configuration.

**Comment by akcheung** [comment]
I believe all nwds slides and videos currently reside under 
/cse/www2/db/nwds. Maybe it's easier to ask support to give us a new 
www-accessible alias for /cse/www2/db so that we don't need to move 
things around?

**Comment by ljorr1** [comment]
I like Alvin's idea. We should ask support for some other domain that points to /cse/www2/db where we can put the stagnant pdfs and videos (maybe db.cs.washington.edu/files/ or something like that). I think any html page can be turned into markdown and put on git.

**Comment by domoritz** [comment]
Can you talk to support to set it up?

**Comment by ljorr1** [comment]
What did you have to do to get the db one redirected and who did you talk to (I think it would be easier to ask that person to do this redirect, as well)?

**Comment by mbalazin** [comment]
I emailed support to do the redirect. I can email them about this one too.

Magdalena Balazinska
Jean Loup Baer Professor of Computer Science and Engineering
Associate Professor, Dept. of Computer Science & Engineering
Director of the IGERT PhD Program in Big Data / Data Science
Senior Data Science Fellow of the eScience Institute
University of Washington

**Comment by domoritz** [comment]
@ljorr1 is this done?

**Comment by ljorr1** [comment]
For now, yes. http://nwds.cs.washington.edu/ is getting data from /cse/www2/db/db2-files, so we can put files there.
