### ISSUE TITLE
add Anant Bhardwaj's talk on datahub to NWDS

### ISSUE THREAD

**Issue by akcheung** [uwdb/website#15]
See earlier email for details.

**Comment by akcheung** [comment]
(and yes yahoo DB Series is still a thing)

**Comment by akcheung** [comment]
Also we need to redirect the current nwds.cs.washington.edu to the new page once it's live.

**Comment by ljorr1** [comment]
When did Anant visit?

**Comment by akcheung** [comment]
1/19/15

**Comment by ljorr1** [comment]
Was this part of the NWDS meeting? And I'll add his info.

**Comment by ljorr1** [comment]
Found it in my email...thanks.
