### ISSUE TITLE
Project icons should be clickable

### ISSUE THREAD

**Issue by domoritz** [uwdb/website#16]
Not just the text.

Btw, looks like we cannot have markdown inside html. Unfortunately.

**Comment by BrandonHaynes** [comment]
Corrected on the project page -- feel free to copy!

**Comment by domoritz** [comment]
I finished a big clean up. We use the same things across the website now. https://github.com/uwdb/website/commit/74b5f679cabacb04eda724b8929b6c849b26fea5

**Comment by stechu** [comment]
Thanks @BrandonHaynes  @domoritz ! 
I  hesitated a bit to do that since I cannot find how to make the CSS+Markdown working. It seems that using hardcoded html is just fine.

**Comment by akcheung** [comment]
[minor] should the project description text be center aligned as well 
similar to the titles?

**Comment by BrandonHaynes** [comment]
I agree -- @domoritz changed the text-align from centered to left-justified in his overnight mega-update; I'm waiting back to hear if it was intentional or an oversight.
