### ISSUE TITLE
"People tiles" should probably be left-justified?

### ISSUE THREAD

**Issue by BrandonHaynes** [uwdb/website#19]
It looks a bit weird for them to have different amounts of whitespace when there aren't enough tiles to wrap.

**Comment by domoritz** [comment]
Do you mean the names on the images?
![screen shot 2015-03-16 at 11 27 42](https://cloud.githubusercontent.com/assets/589034/6673357/8dcbc0dc-cbcf-11e4-9f5a-b660f7bcb3a3.png)

I'm not sure I understand.

**Comment by BrandonHaynes** [comment]
One person's opinion:

![image](https://cloud.githubusercontent.com/assets/1433577/6673427/30928350-cbd0-11e4-812c-f83299b9964b.png)

**Comment by domoritz** [comment]
Oh lol. I don't see that. Totally agree. I probably forgot some prefixed css rules. 

![screen shot 2015-03-16 at 11 34 22](https://cloud.githubusercontent.com/assets/589034/6673455/7276e6d0-cbd0-11e4-8ab7-0df66e59fa4c.png)

**Comment by domoritz** [comment]
@BrandonHaynes I can't reproduce it. Can you add the missing prefixed rule to https://github.com/uwdb/website/blob/gh-pages/css/main.css#L91?

**Comment by BrandonHaynes** [comment]
Corrected by 04e7ab8a5f5e803e43c21fcbafa945f4a529b4f7.  I believe that all the other flexbox styling remains the same.
