### ISSUE TITLE
Use yml for people

### ISSUE THREAD

**Issue by domoritz** [uwdb/website#23]
Because we love databases, let's structure the data more. 

I already did this for faculty https://github.com/uwdb/website/blob/gh-pages/_data/faculty.yml
But we also need to do it for other groups in https://github.com/uwdb/website/tree/gh-pages/_data

**Comment by prup** [comment]
Maybe we should also have a field for Google Scholar in addition to dblp?

**Comment by domoritz** [comment]
Do we use it? I think we actually don't need dblp or googe scholar for non-faculty for now. Imho. The most important thing is getting the full name and the nickname for everybody.

**Comment by domoritz** [comment]
Thanks @mbalazin @BrandonHaynes @jingjingwang @ljorr1 @jortiz16 @jhyrkas @ryanmaas
