### ISSUE TITLE
Links on Project Page Broken

### ISSUE THREAD

**Issue by ljorr1** [uwdb/website#29]
Links on the project page, such as http://db.cs.washington.edu/xml.html, don't work.

**Comment by BrandonHaynes** [comment]
The link target would have been hosted on the older website, which was invalidated when we activated the new site.

I can migrate the content over into new pages here.  The question is whether _all_ of the pages need to be moved over.

**Comment by domoritz** [comment]
Just a note that @ryanmaas moved over the astrodb page.

**Comment by stechu** [comment]
Bump, this hasn't been fixed yet. Where can we find the original page?

**Comment by domoritz** [comment]
Old pages are at `/cse/www2/db/`
