### ISSUE TITLE
Point url to new website

### ISSUE THREAD

**Issue by domoritz** [uwdb/website#3]
Right now db.cs.washington.edu does not point to this website. We've done this for myria.cs.washington.edu before.

**Comment by domoritz** [comment]
@dhalperi What did you tell CSE/UW so that the domain points to the website hosted on Github?

**Comment by dhalperi** [comment]
https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/

**Comment by dhalperi** [comment]
```
dhalperi@dhm dhalperi % dig cname myria.cs.washington.edu

; <<>> DiG 9.8.3-P1 <<>> cname myria.cs.washington.edu
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 38611
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;myria.cs.washington.edu.   IN  CNAME

;; ANSWER SECTION:
myria.cs.washington.edu. 21599  IN  CNAME   uwescience.github.io.

;; Query time: 1001 msec
;; SERVER: 8.8.4.4#53(8.8.4.4)
;; WHEN: Mon Mar 16 10:33:46 2015
;; MSG SIZE  rcvd: 75
```

**Comment by domoritz** [comment]
I sent am email. We are waiting.

**Comment by BrandonHaynes** [comment]
We could do a temporary redirect on the old site while we wait on DNS changes to propagate.

**Comment by akcheung** [comment]
Agreed.

**Comment by domoritz** [comment]
Website is live and I fixed a little issue with ssl (duh).

**Comment by mbalazin** [comment]
The new site looks wonderful!

A few small point:
- data.cs.washington.edu does not seem to re-direct properly. I'll check
  with support.
- The link to AstroDB doesn't work.
- For alumni, we should remove the pictures and make sure to list people
  further back into the past. In particular, please add: Nodira Khoussainova,
  YongChul Kwon, Evan Welbourne, Julie Letchner,  Chris Re, Vibhor Rastogi,
  Nilesh Dalvi, Gerome Miklau, Anhai Doan, Zack Ives, Rachel Pottinger, Mike
  Cafarella, Wolfgang Gatterbauer, Alexandra Meliou, Jayang Madhavan, Peter
  Mork, and Luna Dong.
- I would also prefer that we list people with first name and last name for
  both current and alumni/ae
- For courses, at the Graduate Level, we should separate the regularly
  offered courses from the one time courses. The one-time courses are
  cse590ds, cse599t, and cse599c 2010, cse599c 2006 (the 2010 and 2006 were
  on different topics and should be separated).

thanks,
magda

Magdalena Balazinska
Jean Loup Baer Professor of Computer Science and Engineering
Associate Professor, Dept. of Computer Science & Engineering
Director of the IGERT PhD Program in Big Data / Data Science
Senior Data Science Fellow of the eScience Institute
University of Washington

**Comment by dhalperi** [comment]
@mbalazin : The link works fine for me. (both [data.cs.washington.edu](http://data.cs.washington.edu) and [db.cs.washington.edu](http://data.cs.washington.edu) link well. Maybe your computer has an old DNS mapping since you've checked the link before?

**Comment by domoritz** [comment]
@dhalperi Are you sure? Because we don't have the correct CNAME so it shouldn't work.

**Comment by mbalazin** [comment]
It's possible. Thanks.

Magdalena Balazinska
Jean Loup Baer Professor of Computer Science and Engineering
Associate Professor, Dept. of Computer Science & Engineering
Director of the IGERT PhD Program in Big Data / Data Science
Senior Data Science Fellow of the eScience Institute
University of Washington

**Comment by dhalperi** [comment]
I think actually, I'm just a liar and everything is screwed up for me and not you :p Thanks @domoritz

**Comment by dhalperi** [comment]
Data needs to be a redirect not a CNAME.

**Comment by dhalperi** [comment]
(or make db redirect to data.. either way)

**Comment by dhalperi** [comment]
https://help.github.com/articles/my-custom-domain-isn-t-working/#multiple-domains-in-cname-file

**Comment by domoritz** [comment]
> https://help.github.com/articles/my-custom-domain-isn-t-working/#multiple-domains-in-cname-file

Yes, I saw that. I asked support to set up a redirect.

**Comment by domoritz** [comment]
Fixed. We have a redirect.

**Comment by dansuciu** [comment]
The Website looks amazing.  I really like the DBLP link:)

There are several missing links under “Past Projects”, 
1. The link to XML and semi-structured data doesn’t work, and I don’t think that URL ever existed?

To fix it, unfortunately, I don’t have a single page for those projects, but several. Can you add three links?  They can all be on the same line. If not possible to add three links, then add just the first link:

XPath containment: http://homes.cs.washington.edu/~suciu/project-xpathcontainment.html
XML to Relational mapping http://homes.cs.washington.edu/~suciu/project-rxl.html
XML compression http://homes.cs.washington.edu/~suciu/project-xmill.html
1. AQP,  Semex, Shared/Views, FlowDB: these are old projects ran by Alon, and I don’t don’t know where there website is, if they even have one.
2. Some of Magda’s old projects have missing links: Moire, StreamClean, PEEKS.
3. These projects have missing links: Propagation, Lahar.  They don’t have a URL of their own, but they could all point to Probabilistic databases (http://homes.cs.washington.edu/~suciu/project-querycompilation.html)
4. Remove the last project  • Management of Probabilistic Data, since it’s an active projects.

Dan

**Comment by mbalazin** [comment]
I didn't check all the past links. For lahar, the link should be
http://lahar.cs.washington.edu/

For RFID Ecosystem:
http://rfidecosystem.cs.washington.edu/

thanks,
magda

Magdalena Balazinska
Jean Loup Baer Professor of Computer Science and Engineering
Associate Professor, Dept. of Computer Science & Engineering
Director of the IGERT PhD Program in Big Data / Data Science
Senior Data Science Fellow of the eScience Institute
University of Washington

**Comment by domoritz** [comment]
> - I would also prefer that we list people with first name and last name for
>   both current and alumni/ae

I added tooltips for now at least for faculty. We should refactor the data a bit before we address this properly.

**Comment by domoritz** [comment]
Please create separate issues so that we can assign them to people. Thank you!
