### ISSUE TITLE
People's page on new website

### ISSUE THREAD

**Issue by mbalazin** [uwdb/website#30]
For alumni, we should remove the pictures and make sure to list people further back into the past. In particular, please add: Nodira Khoussainova, YongChul Kwon, Evan Welbourne, Julie Letchner,  Chris Re, Vibhor Rastogi, Nilesh Dalvi, Gerome Miklau, Anhai Doan, Zack Ives, Rachel Pottinger, Mike Cafarella, Wolfgang Gatterbauer, Alexandra Meliou, Jayang Madhavan, Peter Mork, and Luna Dong.

I would also prefer that we list people with first name and last name for both current and alumni/ae

**Comment by domoritz** [comment]
Done
