### ISSUE TITLE
make NWDS talks its own tab

### ISSUE THREAD

**Issue by akcheung** [uwdb/website#38]
Can we make NWDS talks its own tab under menu rather than clicking through events?

**Comment by dhutchis** [comment]
There is a limit on the number of tabs at the top, IIRC. To add a tab means
we must take another away.

**Comment by akcheung** [comment]
Why? There seems to be space for it.

**Comment by domoritz** [comment]
Menu items start to wrap on small screens. We can increase the minimum width or as @dhutchis said drop another item.

**Comment by akcheung** [comment]
How about change "research projects" -> "projects" to make space for 
another "NWDS" tab?

**Comment by domoritz** [comment]
That works as well.
