### ISSUE TITLE
Update People

### ISSUE THREAD

**Issue by stechu** [uwdb/website#39]
Since we have new grads.

**Comment by dhutchis** [comment]
@gunaprsd, @tomerk, @wzcai, Tarun

**Comment by dhutchis** [comment]
Can someone with admin rights to the @uwdb org add the new grads to the uwdb team, so that they can make edits?

**Comment by dhutchis** [comment]
FYI, this is the page http://db.cs.washington.edu/people.html

**Comment by jingjingwang** [comment]
I've sent the invitations out.

**Comment by akcheung** [comment]
merge with #40
