### ISSUE TITLE
Archive graduated students from People

### ISSUE THREAD

**Issue by dhutchis** [uwdb/website#40]
- Brandon Myers
- Seung-He Bae
- Paris Koutris
- Kristi Morton
- others?

Who am I missing?  It would be nice toleave their pictures on the website at the bottom under Alumni, rather than removing their pictures.

**Comment by shrjain** [comment]
Prasang

**Comment by akcheung** [comment]
Alumni:
Seung-Hee
Sudeepa
Eric
Jeremy
Daniel L
Paris
Kristi
Brandon M
Prasang
Shengliang
Brendan L
Yuqing
Dan R

**Comment by domoritz** [comment]
> It would be nice toleave their pictures on the website at the bottom under Alumni, rather than removing their pictures.

We decided to remove pictures for alumni and I think that makes sense. The goal of the pictures is to recognize active members.

**Comment by stechu** [comment]
It would be good to have a link to alumni's website and show their current affiliation tho.

**Comment by akcheung** [comment]
I think right now besides the alumni, Tarun and Cong are the only current students who are missing?
