### ISSUE TITLE
Google Analytics is broken

### ISSUE THREAD

**Issue by dhutchis** [uwdb/website#45]
This code in `_includes/default.html` generates a `TypeError` on page load:

```javascript
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-52534109-1', 'auto');
      ga('send', 'pageview');
```

Do we even use Google Analytics?  If not, let's remove it.

**Comment by domoritz** [comment]
It may be important for grants and such. Not sure so I asked the mailing list.

**Comment by dhutchis** [comment]
The code is still broken. The problem is in the first code, not in the analytics ID.  I checked our Google analytics account and verified that (1) no data is received and (2) we are using the exact code that Google tells us to use.

I'm not sure what to do with this `TypeError: $(...) is not a function`.  Any ideas?

**Comment by dhutchis** [comment]
Okay, I got this working. Turns out the code needs to be in the `<head>`, and it also doesn't work if there is an AdBlocker.

**Comment by domoritz** [comment]
Why does it need to be in the head? Yeh, definitely disable your adblocker.

**Comment by dhutchis** [comment]
Because Google Analytics said so.  I'm not sure.  Maybe it has to do with the order scripts are loaded and run?  The TypeError was there when we put other code in the same script block as the analytics code.  Not sure if these are related.

**Comment by domoritz** [comment]
Hmm, very odd. thanks for looking into it.
