### ISSUE TITLE
Link 590Q course webpage

### ISSUE THREAD

**Issue by dhutchis** [uwdb/website#54]
Does anyone know how to edit the page <https://courses.cs.washington.edu/courses/cse590q/18wi/> so that it points to <http://db.cs.washington.edu/seminars/cse590q/18wi/index.html>? @stechu @gunaprsd 

The former webpage is the "uw official" one. It is also linked to from <http://db.cs.washington.edu/courses.html>

**Comment by akcheung** [comment]
done.

**Comment by stechu** [comment]
👍
